language: c

os:
  - osx

# Keep these dependencies in sync with README.md
before_install:
# https://github.com/travis-ci/travis-ci.github.com/blob/master/docs/user/build-configuration.md#updating-git-submodules
# https://github.com/osxfuse/osxfuse # SUBMODULES note
  - git submodule update --init --recursive
  - brew install autoconf automake libtool gettext
  - brew link --force gettext

script:
  - ./build.sh -t distribution
  - stat /tmp/osxfuse/distribution
